fix for JUnit test error
testSettingsPage	Failure	Settings page is not valid: Model source folder "/TestSeamSettingsPreferencesPage" does not exist.

junit.framework.AssertionFailedError: Settings page is not valid: Model source folder "/TestSeamSettingsPreferencesPage" does not exist.
at org.jboss.tools.seam.ui.test.preferences.SeamSettingsPreferencesPageTest.testSettingsPage(SeamSettingsPreferencesPageTest.java:104)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:21)
at junit.extensions.TestSetup.run(TestSetup.java:25)


git-svn-id: http://svn.jboss.org/repos/jbosstools/trunk@14008 a97e2381-89e5-4abb-bab3-167db6db766c